const Array=[
   
   {url:"error",
   courseId:"123",
   subject:"Computer Science",
   Date:"10/12/2023",
   message:"Last commit message",
   status:"progress",
  },
  { url:"error",
    courseId:"123",
    subject:"Computer Science and Engineering in Artificial Intelligence & Data Science (AI & DS)",
    Date:"10/12/2023",
    message:"Last commit message",
    status:"completed",
  },
  { url:"error",
    courseId:"123",
    subject:"Machine Learning",
    Date:"10/12/2023",
    message:"Last commit message",
    status:"progress",
},
{   url:"error",
    courseId:"123",
    courseId:"123",
    subject:"Computer Science",
    Date:"10/12/2023",
    message:"Last commit message",
    status:"progress",
},
{   url:"error",
    courseId:"123",
    subject:"Computer Science",
    Date:"10/12/2023",
    message:"Last commit message",
    status:"progress",
},
{   url:"error",
    courseId:"123",
    subject:"Computer Science",
    Date:"10/12/2023",
    message:"Last commit message",
    status:"progress",
},
];
 export default Array