export const GET_COURSE = "GET_COURSE";
export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS"
export const HANDLE_COURSE_CHANGE = "HANDLE_COURSE_CHANGE";
export const HANDLE_SUBJECT_CHANGE = "HANDLE_SUBJECT_CHANGE";
