export const HANDLE_LOADING = "HANDLE_LOADING";

export const SETUP_USER = "SETUP_USER";

export const REMOVE_USER = "REMOVE_USER";

export const ALERT = "ALERT";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_LAST_SEEN_NOTIFICATION_ID = "SET_LAST_SEEN_NOTIFICATION_ID";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
